application: com-uchechilaka-docfactory
version: 1
runtime: php55
api_version: 1

env_variables:
    # Set environment variables here
    
skip_files:
- ^(.*/)?releases/.*$

handlers:
- url: /.*
  script: index.php
  
- url: /temp
  static_dir: temp
